### ISSUE TITLE
Create emitter-framework/java component to handle TypeSpec Model

### ISSUE THREAD

**Issue by IlluzionzDev** [IlluzionzDev/typespec#6]
In `emitter-framework/java` there should be a component along the lines of `ModelDeclaration`.

This should take a TypeSpec `Model` type from the TypeSpec compiler, and generate a Java class based on this model. The `Model` should have everything you need such as the name, fields, types etc. The output should be a java model class with a constructor for each field, that can then be instantiated inside our route controllers.

**Comment by M1lney** [comment]
I will mark this as done. There are still improvements to be made but we should have enough here to produce a class from a tsp model.
